version: 0.2
phases:
  install:
    runtime-versions:
      dotnet: 2.2
  pre_build:
    commands:
      - echo Restore started on `date`
      - dotnet restore WebAppForCICD/WebAppForCICD.csproj
  build:
    commands:
      - echo Build started on `date`
      - dotnet publish -c release -o ./build_output WebAppForCICD/WebAppForCICD.csproj
artifacts:
  files:
    - CodeBuild-awsdotnet/build_output/**/*
