version: 0.2
phases:
  install:
    runtime-versions:
      dotnet: 2.2
  pre_build:
    commands:
      - echo Restore started on `date`
      - dotnet restore awsdotnet/WebAppForCICD/WebAppForCICD.csproj
  build:
    commands:
      - echo Build started on `date`
      - dotnet publish -c release -o ./build_output awsdotnet/WebAppForCICD/WebAppForCICD.csproj
